version: '3.8'
services:
  web:
    build: .
    ports:
      - "443:443"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: banking
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
